name: tutorials

channels:
  - astropy

dependencies:
  - python=3.6
  - IPython=6.1.0
  - astropy=3
  - astroquery>=0.3.7
  - matplotlib=2.0.2
  - numpy=1.14
  - scipy=1.0 # needed for coordinates cross-matching
  - jupyter=1.0
  - notebook=5.4
  - aplpy # used in FITS-cube tutorial
  - spectral-cube # used in FITS-cube tutorial
  - reproject # used in FITS-cube tutorial
